### ISSUE TITLE
Remove `_working` or `_draft` from document names and variables

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-GBLS#3]

**Comment by stavros-0** [comment]
I removed working and draft> I am not sure if I should keep No Contact Letter or No Contact Letter Working

**Comment by miabonardi** [comment]
> I removed working and draft> I am not sure if I should keep No Contact Letter or No Contact Letter Working

Thank you! I'll take care of keeping No Contact Letter
